In [ ]:
"""
Solving Ax = b Using LU (or LUP) Decomposition

We want to solve

    Ax = b

where
          [1 2 0]
    A  =  [3 4 4]
          [5 6 3]

and
          [3]
    b  =  [7]
          [8]

--------------------------------------------------
Why don't we solve Ax = b directly?
--------------------------------------------------

In the original system, every equation contains several unknowns:

    x1 + 2x2        = 3
    3x1 + 4x2 + 4x3 = 7
    5x1 + 6x2 + 3x3 = 8

All variables are mixed together.

LU decomposition factors A into

    A = LU

where

    L = lower triangular
    U = upper triangular

Triangular systems are much easier to solve because each row
contains only variables that have already been computed.

The expensive part is computing LU once (O(n^3)).

After that, solving for different b vectors only requires
forward and backward substitution (O(n^2)).

--------------------------------------------------
Step 1: Compute LU
--------------------------------------------------

Start with

          [1 2 0]
    A  =  [3 4 4]
          [5 6 3]

Use row 1 as the first pivot.

Multiplier for row 2:

    l21 = 3

Multiplier for row 3:

    l31 = 5

Perform elimination:

    R2 <- R2 - 3R1

    [3 4 4] - 3[1 2 0]
    [0 -2 4]

    R3 <- R3 - 5R1

    [5 6 3] - 5[1 2 0]
    [0 -4 3]

Matrix becomes

    [1  2  0]
    [0 -2  4]
    [0 -4  3]

Now eliminate below the second pivot.

Multiplier:

    l32 = (-4)/(-2) = 2

Perform

    R3 <- R3 - 2R2

    [0 -4 3] - 2[0 -2 4]
    [0  0 -5]

Therefore

          [1  2  0]
    U  =  [0 -2  4]
          [0  0 -5]

The multipliers form L:

          [1 0 0]
    L  =  [3 1 0]
          [5 2 1]

Verify:

    LU = A

--------------------------------------------------
Step 2: Solve Ly = b
--------------------------------------------------

We solve

          [1 0 0] [y1]   [3]
          [3 1 0] [y2] = [7]
          [5 2 1] [y3]   [8]

Row 1:

    y1 = 3

Row 2:

    3y1 + y2 = 7

    3(3) + y2 = 7

    y2 = -2

Row 3:

    5y1 + 2y2 + y3 = 8

    5(3) + 2(-2) + y3 = 8

    15 - 4 + y3 = 8

    y3 = -3

Therefore

          [ 3]
    y  =  [-2]
          [-3]

This process is called FORWARD SUBSTITUTION.

Why "forward"?

Because we solve

    y1 first,
    then y2,
    then y3.

We move from the top row downward.

--------------------------------------------------
Step 3: Solve Ux = y
--------------------------------------------------

Now solve

          [1  2  0] [x1]   [ 3]
          [0 -2  4] [x2] = [-2]
          [0  0 -5] [x3]   [-3]

Start from the bottom row.

Row 3:

    -5x3 = -3

    x3 = 3/5

Row 2:

    -2x2 + 4x3 = -2

    -2x2 + 4(3/5) = -2

    -2x2 + 12/5 = -2

    -2x2 = -22/5

    x2 = 11/5

Row 1:

    x1 + 2x2 = 3

    x1 + 2(11/5) = 3

    x1 + 22/5 = 15/5

    x1 = -7/5

Therefore

          [-7/5]
    x  =  [11/5]
          [ 3/5]

This process is called BACKWARD SUBSTITUTION.

Why "backward"?

Because we solve

    x3 first,
    then x2,
    then x1.

We move from the bottom row upward.

--------------------------------------------------
Why does LU solving work?
--------------------------------------------------

Since

    A = LU

the original system

    Ax = b

becomes

    LUx = b

Define

    y = Ux

Then

    Ly = b

which is easy to solve by forward substitution.

After finding y, solve

    Ux = y

by backward substitution.

Instead of solving one complicated system, we solve two
simple triangular systems.
"""

In [ ]:
def lup_solve(L, U, pi, b):
    n = len(b)

    y = [0.0] * n
    x = [0.0] * n

    # Forward substitution: Ly = Pb
    for i in range(n):
        y[i] = b[pi[i]]

        for j in range(i):
            y[i] -= L[i][j] * y[j]

    # Backward substitution: Ux = y
    for i in range(n - 1, -1, -1):
        x[i] = y[i]

        for j in range(i + 1, n):
            x[i] -= U[i][j] * x[j]

        x[i] /= U[i][i]

    return x